### ISSUE TITLE
Authenticating...

### ISSUE THREAD

**Issue by prov3it** [PrimalZed/kobo-book-downloader-vue#2]
Hi PrimalZed,

We are back. Now the message is "Authenticating..." after pressing the login button. Used 2 different browsers, same issue.

![Screenshot](https://github.com/user-attachments/assets/c9d13a89-70c1-4853-ace3-8b264c00c46f)

**Comment by mommalicious** [comment]
I get the same problem.

**Comment by PrimalZed** [comment]
Thank you for the report. It looks like a new security update on authorize.kobo.com. I'll see what I can work out, but there might not be a way around this.

**Comment by PrimalZed** [comment]
Created a new release v1.2.0 with new sign-in method:
https://github.com/PrimalZed/kobo-book-downloader-vue/releases/tag/v1.2.0

Ultimately, might be better to have an application that Windows launches for the `kobo://` url, but that would need an installed Windows application.

**Comment by mommalicious** [comment]
Thank you very much PrimalZed!

**Comment by prov3it** [comment]
Thank you @PrimalZed. Still can't buy you a coffee? ;-)
