### ISSUE TITLE
the list of audiobook and book doesnt show all the resourses

### ISSUE THREAD

**Issue by heluq** [PrimalZed/kobo-book-downloader-vue#4]
I have comfirmed the problem is the list only can show the limits number of the books, and another problem is like this kind of book https://www.kobo.com/es/es/ebook/25-cuentos-populares-de-espana-para-descubrir-su-historia-1, the epub file is not correct, text and background picture is apart.

**Comment by PrimalZed** [comment]
Thank you for bringing this to my attention. I did a small fix for getting more records from the kobo sync api, but since I only have 33 items on my account, I still get everything on the first request.

Can you try the [new v1.2.1 release](https://github.com/PrimalZed/kobo-book-downloader-vue/releases/tag/v1.2.1) to see if that works? Can you check whether you get more than one `sync` request, and what the responses for each request are?

Also, I bought the book you linked there, and it shows up fine when I log in with my account:
![image](https://github.com/user-attachments/assets/1891aa16-cb2e-469c-aee3-5458c7d5bba1)

**Comment by heluq** [comment]
Hi,
I believe the issue lies with the kepub format itself. Most standard EPUB readers cannot display kepub content correctly. So far, I’ve found that only the Calibre viewer can render it properly. And with the fix, the list of books show the correct way. I can recieve more than one sync.

Secondly, for some books—like this one: https://www.kobo.com/es/es/ebook/sherlock-holmes-el-hombre-del-labio-retorcido-spanish-english the saved filename does not match the actual book title.
![image_788](https://github.com/user-attachments/assets/c8c85581-21ed-48a0-92cb-2670b52b7df0)

Third, there’s a bug. A book that is no longer in my library but previously existed in the Archives still shows up in the program web interface. The program incorrectly identifies it as unauthorized to download, the web interface either freezes the download button or displays a “Not Authorized” message, causing the page to become unresponsive.
![image_790](https://github.com/user-attachments/assets/a5e3a76d-adde-44cc-a511-8fd2d65b34e8)
![image_789](https://github.com/user-attachments/assets/d26d1f83-90ac-4c9e-b7fb-261ae91e63e9)

Lastly, could you consider adding a feature to allow batch downloads? Currently, books must be downloaded one by one. I understand that implementing this may involve setting a logic for which version should be downloaded by default, and if that version isn’t available, which one should be next.

Thank you for your attention and efforts.

**Comment by PrimalZed** [comment]
It sounds like the issue of listing all books/audiobooks in your account has been resolved, so I will close this issue.

## Filename
I'm guessing that filename is from the "Download DRM Free" link? If so, that's the filename used by Kobo in the direct download link.

## Book not in library is listed
This is probably a bug on Kobo's side. I don't know what, if anything, would indicate in the Kobo API response that you don't actually have access to the book before attempting to download the epub file.

## Batch / queued downloads
You can open up a new issue for this feature request, but I currently don't plan on implementing that.
